site_name: THEOPHYSICS Research Hub
site_description: "David Lowe's breakthrough research on Quantum-Consciousness-Prophecy interface"
site_author: David Lowe
site_url: https://theophysics.pages.dev/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/YellowKidokc/MK-Docs-Obsidian-
repo_name: YellowKidokc/THEOPHYSICS

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YellowKidokc
  generator: false

copyright: Copyright &copy; 2025 David Lowe - THEOPHYSICS Research

nav:
  - Home: index.md
  - Research:
      - Overview: research/index.md
      - Foundation Crisis: research/foundation-crisis.md
      - Entangled Soul: research/entangled-soul.md
      - 10 Universal Laws: research/10-universal-laws.md
  - Databases:
      - QSF Schema: data/qsf-schema.md
      - EOW Schema: data/eow-schema.md
  - About: about.md
  - Tags: tags.md