site_name: Theophysics MkDocs Pipeline
site_description: "Automation for multi-site MkDocs publishing from an Obsidian vault"
site_author: David Lowe
site_url: https://theophysics.pages.dev/

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
  features:
    - navigation.top
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

nav:
  - Overview: index.md
