obsidian_entrypoint_path_str: "O:/THEOPHYSICS/General Relativity and Quantum dynamics solved/index.md"
toggles:
  process_all: true
md_folder_path_str: "O:/THEOPHYSICS/General Relativity and Quantum dynamics solved/output/md"
html_output_folder_path_str: "O:/THEOPHYSICS/General Relativity and Quantum dynamics solved/output/html"
md_entrypoint_path_str: "O:/THEOPHYSICS/General Relativity and Quantum dynamics solved/output/md/index.md"
